// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL6n7vQwMW-3hZHHaDVaIfOy-nNy9xEUU',
    appId: '1:114418483993:web:af9f2a73052ace97377b88',
    messagingSenderId: '114418483993',
    projectId: 'financeapp-1a0e3',
    authDomain: 'financeapp-1a0e3.firebaseapp.com',
    storageBucket: 'financeapp-1a0e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsR0kue5fZV1rWL7mMixnIW2JEVlPJAns',
    appId: '1:114418483993:android:45c29a9e6c3a2512377b88',
    messagingSenderId: '114418483993',
    projectId: 'financeapp-1a0e3',
    storageBucket: 'financeapp-1a0e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-7i2lKYCfEfEE2qJkCkkLQCNcEB5q1m8',
    appId: '1:114418483993:ios:beb3e3c285dd8f45377b88',
    messagingSenderId: '114418483993',
    projectId: 'financeapp-1a0e3',
    storageBucket: 'financeapp-1a0e3.appspot.com',
    iosBundleId: 'com.example.finance',
  );
}
